### ISSUE TITLE
Add D-M-test.zip to test models

### ISSUE THREAD

**Issue by e-perl-NOAA** [nmfs-ost/ss3-test-models#54]
@Rick-Methot-NOAA suggested adding the 
[D-M_test.zip](https://github.com/nmfs-ost/ss3-test-models/files/13719343/D-M_test.zip) to the test model files in ss3-source-code PR [#542](https://github.com/nmfs-ost/ss3-source-code/pull/542). 

@Rick-Methot-NOAA can you tell me more about this model?

**Comment by e-gugliotti-NOAA** [comment]
Simple model with generalized size comp data with D-M

**Comment by Rick-Methot-NOAA** [comment]
This model is a derivative of simple.

- two areas with identical fisheries and surveys in both areas
- two seasons of unequal durations with all catch in season 1
- adds fleet 7 as a depletion survey
- adds generalized size comp data in same units as the length comp data (2 cm bins).  Data are identical to the length comp data, so logL should be the same.
- adds D-M for fleets 1, 2, 3, 4 and all use the same shared parameter.
- note that fleet 3 has no comp data so D-M is irrelevant; note that fleet 5 has comp data but does not have D-M so provides a comparison to fleet 2.
